language: python
python:
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
# command to install dependencies
install:
  - pip install -r test-requirements.txt
  - pip3 install http://download.pytorch.org/whl/cpu/torch-0.4.1-cp36-cp36m-linux_x86_64.whl
# command to run tests
script:
  - python tests/pytests_data.py
  - python tests/pytests_trainer.py
  - python tests/pytests_transforms.py
  - python tests/pytests_multihead.py
